# Include dependencies when building wheels on cibuildwheel
[build-system]
requires = [
    "setuptools",
    "Cython>=0.19",
    "numpy>=2.0.0rc1",
    "h5py>=2.4.0",
]

build-backend = "setuptools.build_meta"
